// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TipsaNu.Infrastructure.Persistence;

#nullable disable

namespace TipsaNu.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602132926_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TipsaNu.Domain.Entities.Competitor", b =>
                {
                    b.Property<int>("CompetitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompetitorId"));

                    b.Property<bool>("IsIndividual")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CompetitorId");

                    b.ToTable("Competitors", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.ExtraBet", b =>
                {
                    b.Property<int>("ExtraBetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExtraBetId"));

                    b.Property<int>("OptionId")
                        .HasColumnType("integer");

                    b.Property<int?>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ExtraBetId");

                    b.HasIndex("OptionId");

                    b.HasIndex("UserId");

                    b.ToTable("ExtraBets", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.ExtraBetOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OptionId"));

                    b.Property<bool>("AllowCustomChoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("OptionId");

                    b.HasIndex("MatchId");

                    b.HasIndex("TournamentId");

                    b.ToTable("ExtraBetOptions", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.ExtraBetOptionChoice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChoiceId"));

                    b.Property<int>("OptionId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ChoiceId");

                    b.HasIndex("OptionId");

                    b.ToTable("ExtraBetOptionChoices", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.ExtraBetOptionCorrectValue", b =>
                {
                    b.Property<int>("CorrectValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CorrectValueId"));

                    b.Property<int>("OptionId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CorrectValueId");

                    b.HasIndex("OptionId");

                    b.ToTable("ExtraBetOptionCorrectValues", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<int>("MaxTeams")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.GroupCompetitor", b =>
                {
                    b.Property<int>("GroupCompetitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupCompetitorId"));

                    b.Property<int>("CompetitorId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("GroupCompetitorId");

                    b.HasIndex("CompetitorId");

                    b.HasIndex("GroupId", "CompetitorId")
                        .IsUnique();

                    b.ToTable("GroupCompetitors", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.GroupStanding", b =>
                {
                    b.Property<int>("StandingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StandingId"));

                    b.Property<int>("CompetitorId")
                        .HasColumnType("integer");

                    b.Property<int>("Draw")
                        .HasColumnType("integer");

                    b.Property<int>("GoalDifference")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Lost")
                        .HasColumnType("integer");

                    b.Property<int>("Played")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Won")
                        .HasColumnType("integer");

                    b.HasKey("StandingId");

                    b.HasIndex("CompetitorId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupStanding", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.LeaderboardEntry", b =>
                {
                    b.Property<int>("LeagueMemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.HasKey("LeagueMemberId");

                    b.ToTable("LeaderboardEntries", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeagueId"));

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("InvitationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("LeagueId");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Leagues", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.LeagueMember", b =>
                {
                    b.Property<int>("LeagueMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LeagueMemberId"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LeagueMemberId");

                    b.HasIndex("UserId");

                    b.HasIndex("LeagueId", "UserId")
                        .IsUnique();

                    b.ToTable("LeagueMembers", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatchId"));

                    b.Property<int>("AwayCompetitorId")
                        .HasColumnType("integer");

                    b.Property<int?>("DependsOnMatch1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("DependsOnMatch2Id")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeCompetitorId")
                        .HasColumnType("integer");

                    b.Property<int>("MatchType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PredictionDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreAway")
                        .HasColumnType("integer");

                    b.Property<int?>("ScoreHome")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<int?>("WinnerCompetitorId")
                        .HasColumnType("integer");

                    b.HasKey("MatchId");

                    b.HasIndex("AwayCompetitorId");

                    b.HasIndex("DependsOnMatch1Id");

                    b.HasIndex("DependsOnMatch2Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("HomeCompetitorId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WinnerCompetitorId");

                    b.ToTable("Matches", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.PointRule", b =>
                {
                    b.Property<int>("PointRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PointRuleId"));

                    b.Property<string>("Criterion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("PointRuleId");

                    b.HasIndex("TemplateId");

                    b.ToTable("PointRules", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Prediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PredictionId"));

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("PointsAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("PredictedAwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("PredictedHomeScore")
                        .HasColumnType("integer");

                    b.Property<int?>("PredictedWinnerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PredictionId");

                    b.HasIndex("MatchId");

                    b.HasIndex("PredictedWinnerId");

                    b.HasIndex("UserId");

                    b.ToTable("Predictions", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TournamentId"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("TournamentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Tournaments", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.TournamentCompetitor", b =>
                {
                    b.Property<int>("TournamentCompetitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TournamentCompetitorId"));

                    b.Property<int>("CompetitorId")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("TournamentCompetitorId");

                    b.HasIndex("CompetitorId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentCompetitors");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.TournamentTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemplateId"));

                    b.Property<int>("AdvancingPerGroup")
                        .HasColumnType("integer");

                    b.Property<bool>("AllowsBestThird")
                        .HasColumnType("boolean");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalGroups")
                        .HasColumnType("integer");

                    b.HasKey("TemplateId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("TournamentTemplates", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.TournamentTiebreaker", b =>
                {
                    b.Property<int>("TiebreakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TiebreakerId"));

                    b.Property<string>("Criterion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("TiebreakerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentTiebreakers", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.ExtraBet", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.ExtraBetOption", "ExtraBetOption")
                        .WithMany("ExtraBets")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.User", "User")
                        .WithMany("ExtraBets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExtraBetOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.ExtraBetOption", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TipsaNu.Domain.Entities.Tournament", "Tournament")
                        .WithMany("ExtraBetOptions")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.ExtraBetOptionChoice", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.ExtraBetOption", "ExtraBetOption")
                        .WithMany("ExtraBetOptionChoices")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExtraBetOption");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.ExtraBetOptionCorrectValue", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.ExtraBetOption", "ExtraBetOption")
                        .WithMany("ExtraBetOptionCorrectValues")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExtraBetOption");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Group", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Groups")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.GroupCompetitor", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.Competitor", "Competitor")
                        .WithMany("GroupCompetitors")
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.Group", "Group")
                        .WithMany("GroupCompetitors")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Competitor");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.GroupStanding", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.Competitor", "Competitor")
                        .WithMany("GroupStandings")
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.Group", "Group")
                        .WithMany("GroupStandings")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Competitor");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.LeaderboardEntry", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.LeagueMember", "LeagueMember")
                        .WithOne("LeaderboardEntry")
                        .HasForeignKey("TipsaNu.Domain.Entities.LeaderboardEntry", "LeagueMemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LeagueMember");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.League", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.User", "AdminUser")
                        .WithMany("AdminLeagues")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Leagues")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AdminUser");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.LeagueMember", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.League", "League")
                        .WithMany("Members")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.User", "User")
                        .WithMany("LeagueMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Match", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.Competitor", "AwayCompetitor")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayCompetitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.Match", "DependsOnMatch1")
                        .WithMany()
                        .HasForeignKey("DependsOnMatch1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TipsaNu.Domain.Entities.Match", "DependsOnMatch2")
                        .WithMany()
                        .HasForeignKey("DependsOnMatch2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TipsaNu.Domain.Entities.Group", "Group")
                        .WithMany("Matches")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TipsaNu.Domain.Entities.Competitor", "HomeCompetitor")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeCompetitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.Competitor", "WinnerCompetitor")
                        .WithMany("WinningMatches")
                        .HasForeignKey("WinnerCompetitorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayCompetitor");

                    b.Navigation("DependsOnMatch1");

                    b.Navigation("DependsOnMatch2");

                    b.Navigation("Group");

                    b.Navigation("HomeCompetitor");

                    b.Navigation("Tournament");

                    b.Navigation("WinnerCompetitor");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.PointRule", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.TournamentTemplate", "Template")
                        .WithMany("PointRules")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.Match", "Match")
                        .WithMany("Predictions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.Competitor", "PredictedWinner")
                        .WithMany()
                        .HasForeignKey("PredictedWinnerId");

                    b.HasOne("TipsaNu.Domain.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("PredictedWinner");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.TournamentTemplate", "Template")
                        .WithMany("Tournaments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.TournamentCompetitor", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.Competitor", "Competitor")
                        .WithMany("TournamentCompetitors")
                        .HasForeignKey("CompetitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TipsaNu.Domain.Entities.Tournament", "Tournament")
                        .WithMany("TournamentCompetitors")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competitor");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.TournamentTemplate", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.TournamentTiebreaker", b =>
                {
                    b.HasOne("TipsaNu.Domain.Entities.Tournament", "Tournament")
                        .WithMany("TournamentTiebreakers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Competitor", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("GroupCompetitors");

                    b.Navigation("GroupStandings");

                    b.Navigation("HomeMatches");

                    b.Navigation("TournamentCompetitors");

                    b.Navigation("WinningMatches");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.ExtraBetOption", b =>
                {
                    b.Navigation("ExtraBetOptionChoices");

                    b.Navigation("ExtraBetOptionCorrectValues");

                    b.Navigation("ExtraBets");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Group", b =>
                {
                    b.Navigation("GroupCompetitors");

                    b.Navigation("GroupStandings");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.League", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.LeagueMember", b =>
                {
                    b.Navigation("LeaderboardEntry")
                        .IsRequired();
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Match", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("ExtraBetOptions");

                    b.Navigation("Groups");

                    b.Navigation("Leagues");

                    b.Navigation("Matches");

                    b.Navigation("TournamentCompetitors");

                    b.Navigation("TournamentTiebreakers");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.TournamentTemplate", b =>
                {
                    b.Navigation("PointRules");

                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("TipsaNu.Domain.Entities.User", b =>
                {
                    b.Navigation("AdminLeagues");

                    b.Navigation("ExtraBets");

                    b.Navigation("LeagueMemberships");

                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
